
term=xterm-256color
font=Monospace:size=10
#font-bold=Monospace:size=14 font-italic=Monospace:size=14
#font-bold-italic=Monospace:size=14
[cursor]
style=block
[main]

[colors-dark]
alpha=0.6
regular0=0f1417
regular1=ff729e
regular2=7af488
regular3=fff672
regular4=75bce7
regular5=1c5070
regular6=90cef4
regular7=eff9ff
bright0=929a9e
bright1=ff9fbd
bright2=a5ffb0
bright3=fff9a5
bright4=a6ddff
bright5=b5e3ff
bright6=cfedff
bright7=f8fcff

dim-blend-towards=black
